### PR TITLE
Further tweaks to Basic-1D-Fitting tutorials

### PR DESCRIPTION
**Pull request by smk78**
This PR addresses the tweaks suggested by @butlerpd in https://github.com/SasView/tutorials/pull/14#issuecomment-2304837663.

### CODE REVIEW

**Comment by butlerpd** [comment]
I am confused. I see that the typo seems to have been fixed and the red line on the residual plot properly assigned to +/- 3 instead of 2, but otherwise it looks like the 6.0 version is an update to an old version of the tutorial for 6.0? The plots are now back to being the ones from b1 (without the new logo) and the text around example 2 looks like it did before it was changed to reflect the currently agreed results (chi^2 less than 1 and vol frac of order 17%).
Am I missing something?  A quick look at 5.0 suggests it too is back to the old version (from before the last PR).

Were the wrong versions uploaded as "new?" or the wrong versions used as the starting point to do "further tweaks?" or am I misunderstanding or misremembering?

**Comment by smk78** [comment]
@butlerpd wrote:
> I am confused... Were the wrong versions uploaded as "new?" or the wrong versions used as the starting point to do "further tweaks?"

Ahem. Umm. Yes! Whoops-a-daisy! Re-doing them now.

**Comment by smk78** [comment]
@wpotrzebowski wrote:
> Two comments from students (to the previous version)
> 
> 1. In example 2 in the SLD calculation part. It says click on "Calculate" button, which doesn't exist. 

Ooo, good catch! Thanks! The ```Calculate``` button was a v4 thang. Have removed it from the v5 & v6 tutorials.

> Then some students thought that SLD will automatically get updated in respective parameters fields (_sld_ and _sld_solvent_). I am not sure if we can better explain it?

A few lines lower on the same page as the now removed Calculate I have changed it to read:
'Enter these values in the FitPage (they are not auto-populated from the SLD Calculator).'

> 2. Some students didn't understand what do we mean by "nonsensical uncertainties". I think we should just say something like "uncertainties make no sense" even though it doesn't sound nice.

Done.

**Comment by smk78** [comment]
In https://github.com/SasView/tutorials/pull/14#issuecomment-2304837663 @butlerpd wrote:
> ...The resolution of the images is quite low...

The screenshots have now also been re-done at the same resolution and in the same way as those in the v6 document.

**Comment by wpotrzebowski** [comment]
I haven't read the entire thing but I looked at the latest changes (since I read it last). They look good.

**Review by wpotrzebowski — APPROVED** [review]

**Comment by smk78** [comment]
Agreed at Leadership Team meeting 15/10/24 to merge this without further review.

**Pull request merged**
